### ISSUE TITLE
How could get different branch deployment status?

### ISSUE THREAD

**Issue by elkan1788** [therealsujitk/vercel-badge#5]
Thanks for you project let us get more fun with brage status.

But there found a problem, if there so many branch in one project ,  how to set different branch deployment status, hope there can give some help, thanks.

**Comment by therealsujitk** [comment]
In Vercel each branch is deployed on a different URL (Ex: `https://site-git-master-username.vercel.app`). In this case the `APP_NAME` will be `site-git-master-username`.

You can view the deployment domains in the deployment page at Vercel.

![image](https://user-images.githubusercontent.com/60378235/175301955-b4cb3ac0-7e63-444a-b854-74023ef10b4d.png)

**Comment by elkan1788** [comment]
Got it and working now, thanks.
