### ISSUE TITLE
Add option to change name next to vercel logo

### ISSUE THREAD

**Issue by Snailedlt** [therealsujitk/vercel-badge#8]
In a world where monorepos are more and more common, and have good support in vercel, you often times have multiple deployments per repo.

#### Code
```md
Website: ![Vercel Website](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos-web)

API: ![Vercel API](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos)
```
#### Preview
Website: ![Vercel Website](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos-web)

API: ![Vercel API](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos)

#### Code
```md
Website: ![Vercel Website](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos-web&title=website)

API: ![Vercel API](https://therealsujitk-vercel-badge.vercel.app/?app=markdown-videos&title=API)
```
#### Preview
![Vercel Website](https://img.shields.io/badge/web-deployed-44cc11?logo=vercel)
![Vercel API](https://img.shields.io/badge/API-deployed-44cc11?logo=vercel)

**Comment by therealsujitk** [comment]
@Snailedlt you can now use the **`?name=`** parameter to do this. Also, be sure to check out the [badge generator](https://therealsujitk-vercel-badge.vercel.app) to create your badge quickly and easily.

**Comment by Snailedlt** [comment]
Perfect, that's exactly what I needed!
Nice little web interface too!
